#!/bin/bash

set -e
sudo ls

CHECK_VAL=$(grep -cP '(vmx|svm)' /proc/cpuinfo)
if [ "$CHECK_VAL" -eq 0 ]; then
    echo "[1/4] break ~ device unable to virtualize"
    exit 1
fi

echo "[1/4] virtualization ! Ok"

if (! lsmod | grep kvm &> /dev/null); then
    echo "[2/4] break ~ kvm not enabled, try: modprobe kvm"
    exit 1
fi

echo "[2/4] kvm            ! Ok"

if ! rpm -q qemu-kvm libvirt virt-install &> /dev/null ; then
    sudo dnf install -y @virtualization
fi

sudo systemctl enable --now libvirtd 
sudo usermod -aG libvirt $USER

echo "[3/4] dependencies   ! Ok"

if [ ! -f ./images/*.qcow2 ] ; then
    echo "[4/4] needs rhel guest-image"
    exit 1 
fi

echo "[4/4] image          ! Ok"

echo ""
echo -e "\e[38;5;208m谢谢光临, 欢迎下次再来。\e[0m"
